export default {
  BACKGROUND_PRIMARY: "#1D1F2E",
  BACKGROUND_SECONDARY: "#6B6D88",
  TEXT_PRIMARY: "#FFFEFE",
  TEXT_SECONDARY: "#6B6D88",
  TEXT_LIGHT: "#D3D4D7",
  MORNING: "#FFEADA",
  NIGHT: "#363946",
};
