export default {
  BACKGROUND_PRIMARY: "#FEFEFE",
  BACKGROUND_SECONDARY: "#FFFFFF",
  TEXT_PRIMARY: "#1D1F2E",
  TEXT_SECONDARY: "#D3D2D7",
  TEXT_TERTIARY: "#C3B9B5",
  ORANGE: "#FA941F",
  PURPLE: "#8F9EF0",
  GRAY_DARK: "#6A6C88",
};
