export default {
  BACKGROUND_PRIMARY: "#FFFEFE",
  BACKGROUND_SECONDARY: "#F6F6FC",
  TEXT_PRIMARY: "#1D1F2E",
  TEXT_SECONDARY: "#A29B97",
  TEXT_LIGHT: "#B4B5BB",
  MORNING: "#FFEADA",
  NIGHT: "#363946",
};
